FROM golang:1.17-alpine as build-stage

RUN mkdir -p /app

WORKDIR /app

COPY . /app

RUN go mod download

WORKDIR /app/grpc-server

RUN go build -o grpc-server


EXPOSE 50051

ENTRYPOINT [ "/grpc-server" ]
